#!/usr/bin/env bash
# -*- python -*-
""":"
exec casa -c "$0" "$@"
"""
from argparse import ArgumentParser
from pathlib import Path

print("Hello from casa")

def get_target_name(vis_path: Path) -> str:
    tb = table()
    tb.open(str(vis_path / "FIELD"))
    name = str(tb.getcol("NAME")[0])
    tb.close()

    name = name.replace(" ", "_")
    if name.startswith("field_"):
        name = name.replace("field_", "")
    return name

def get_parser() -> ArgumentParser:
    parser = ArgumentParser(description="A dummy script using casacore")

    parser.add_argument("ms", type=Path, help="Path to a MeasurementSet.")

    return parser

def main() -> None:
    parser = get_parser()
    args = parser.parse_args()

    _ = get_target_name(
        vis_path=args.ms,
    )


if __name__ == "__main__":
    main()